const INVENTORY_MOVEMENT_TYPE_USER_PURCHASE = 'USER_PURCHASE'
const INVENTORY_MOVEMENT_TYPE_ADMIN_ADD_STOCK = 'ADD_STOCK'
const INVENTORY_MOVEMENT_TYPE_ADMIN_REDUCE_STOCK = 'REDUCE_STOCK'

export {
  INVENTORY_MOVEMENT_TYPE_USER_PURCHASE,
  INVENTORY_MOVEMENT_TYPE_ADMIN_ADD_STOCK,
  INVENTORY_MOVEMENT_TYPE_ADMIN_REDUCE_STOCK,
}
